### ISSUE TITLE
Implementing setters + adding tests

### ISSUE THREAD

**Issue by zacharyfmarion** [KusStar/react-native-fast-url#1]
Hey! Great project...fun fact I was halfway through implementing the exact same thing (using the same c++ library) when I realized it had already been done...great minds 😄. Just wanted to quickly check whether you would be okay with me putting up a PR to add support for all the setter methods and adding some unit tests that run in the example app (similar to [here](https://github.com/zacharyfmarion/react-native-fast-trie/tree/main/example/src/screens/Tests/tests)). I'm a bit hesitant to integrate this library at my company without any testing.

**Comment by KusStar** [comment]
Yes! I was too busy to add it before.
It would great if you make a PR for tests.
Please feel free to make it.
